name: Despliegue a GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar Astro
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto Astro
        run: npm run build

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          access_token: ${{ secrets.TOKEN_GITHUB }}
          branch: gh-pages
          folder: build

